import { Box3, Color, Scene, Vector2, Vector3 } from 'three/webgpu';
import { readConfig } from './core/config';
import { EventBus, type QualityTier } from './core/events';
import { FrameLoop } from './core/loop';
import { FirstPersonCamera } from './camera/firstPersonCamera';
import { InteractionSystem } from './interaction/interactionSystem';
import { TextureLibrary } from './loading/textureLibrary';
import { LightPool } from './render/lightPool';
import { createMaterials } from './render/materials';
import { loadArt } from './render/art';
import { ProbeManager } from './render/probe';
import { createRenderer, PostStack } from './render/renderer';
import { PlayerController, createPlayerState } from './player/controller';
import { Input } from './player/input';
import { DoorSystem } from './world/doors';
import { initGlbLoader } from './loading/glbZone';
import { buildZoneGraph, startZone, type AssetManifest } from './world/zoneGraph';
import { ZoneManager } from './world/zoneManager';
import { Hud } from './ui/hud';
import { AudioEngine } from './audio/audioEngine';
import { GameView } from './ui/gameView';
import { registerGames } from './games/registry';
import { GameSessionManager, Wallet } from './games/shared/session';
import type { CasinoTableExtras } from './interaction/schema';
import { assetUrl } from './loading/assetUrl';
import { initTableAssets } from './tables/assets';
import { pickRouletteBet } from './tables/layoutPick';

async function main() {
  const config = readConfig();
  const bus = new EventBus();
  const canvas = document.getElementById('viewport') as HTMLCanvasElement;

  const input = new Input(canvas);
  let tier: QualityTier = config.quality;

  const { renderer, backend } = await createRenderer(canvas, config.forceWebGL);
  const scene = new Scene();
  scene.background = new Color(0x050302);

  const player = createPlayerState({ x: 0, y: 0, z: 0 }, 0);
  const fpCamera = new FirstPersonCamera(player);
  const post = new PostStack(renderer, scene, fpCamera.camera);

  let audio: AudioEngine | null = null;
  const hud = new Hud(bus, {
    requestLock: () => { audio?.start(); void input.lock(); }, // user gesture: also unlocks audio
    setVolume: (v) => audio?.setVolume(v),
    setQuality: (t) => { tier = t; post.setTier(t); bus.emit('quality:changed', { tier: t }); },
    setSensitivity: (v) => { input.sensitivity = v; },
    setFov: (v) => fpCamera.setFov(v),
  }, tier);
  document.addEventListener('pointerlockchange', () => hud.setLocked(input.isLocked));

  // ---- initial load: textures → materials → lobby only; the rest of the mansion streams (§8)
  hud.setStatus('Polishing the marble…');
  const textures = new TextureLibrary(renderer.getMaxAnisotropy());
  await Promise.all([
    textures.load(assetUrl('/assets/textures/textures.json'), (d, t) => hud.setStatus(`Polishing the marble… ${Math.round((d / t) * 100)}%`)),
    document.fonts.load("500 48px 'Cinzel'"), // door plaques are drawn with it
    loadArt(assetUrl('/assets/art/art.json'), renderer.getMaxAnisotropy()),
  ]);
  const materials = createMaterials(textures);
  initTableAssets(textures);   // cards, chips, reels, ball for the 3D tables (src/tables)
  initGlbLoader(renderer);
  // generated by `npm run build:assets`; the mansion still works (code zones only) without it
  const manifest: AssetManifest = await fetch(assetUrl('/assets/manifest.json')).then((r) => (r.ok ? r.json() : { zones: {} }), () => ({ zones: {} }));

  const lights = new LightPool(scene, fpCamera.camera);
  const probes = new ProbeManager(renderer, scene, 0.35);
  const interaction = new InteractionSystem(fpCamera.camera, input, bus);
  const zones = new ZoneManager(buildZoneGraph(manifest), { scene, renderer, camera: fpCamera.camera, bus, player, materials, lights, probes, interaction });
  const doors = new DoorSystem(zones, player, bus);
  zones.doors = doors;
  interaction.register('door', {
    prompt: (e) => doors.promptFor(String(e.doorId)),
    activate: (e) => doors.activate(String(e.doorId)),
  });
  const controller = new PlayerController(player, input, zones.collisionWorld);

  // ---- audio (Phase 6): zone beds, positional emitters, door + game sounds
  audio = new AudioEngine(fpCamera.camera, () => zones.visibleSounds());
  bus.on('zone:entered', ({ zoneId }) => audio?.setZone(zoneId));
  bus.on('door:moved', ({ opening, position }) => audio?.play(opening ? 'doorOpen' : 'doorClose', { ...position, y: 1.5 }, 0.8));
  addEventListener('keydown', (e) => {
    if (e.code === 'KeyM' && !e.repeat && audio) bus.emit('ui:toast', { text: audio.toggleMute() ? 'Sound muted — press M to restore' : 'Sound on' });
  });

  // ---- games (Phase 5): world → interaction → session → engine; the UI only presents (§9)
  const wallet = new Wallet(loadChips());
  const sessions = new GameSessionManager(wallet, Math.random);
  registerGames(sessions);
  const gameView = new GameView(wallet);
  let seatedAt: string | null = null;
  let targetExposure = 1;
  let seatedGame: string | null = null;
  const leaveTable = () => {
    if (!seatedAt) return;
    void zones.gameState(seatedAt, null, []);   // clear the felt
    sessions.close(seatedAt);
    seatedAt = null;
    seatedGame = null;
    saveChips(wallet.balance);
    gameView.hide();
    fpCamera.setSeat(null);
    lights.setFeature(null);
    lights.setDim(null);
    targetExposure = 1;
    hud.setInGame(false);
    // Re-lock the mouse; if the browser refuses (e.g. the gesture was Esc), fall back to the pause menu.
    void input.lock().finally(() => setTimeout(() => { if (!input.isLocked) hud.setLocked(false); }, 250));
  };
  gameView.onLeave = leaveTable;
  // roulette: place chips by clicking the printed layout (the pointer is free while seated)
  canvas.addEventListener('click', (e) => {
    if (!seatedAt || seatedGame !== 'roulette' || input.isLocked) return;
    const ndc = new Vector2((e.clientX / innerWidth) * 2 - 1, -(e.clientY / innerHeight) * 2 + 1);
    const bet = pickRouletteBet(zones.anchorsFor(seatedAt), fpCamera.camera, ndc, gameView.ui.stake);
    if (bet) gameView.send({ type: 'bet', bet });
  });
  interaction.register('casinoTable', {
    prompt: (e) => e.interactionPrompt,
    activate: (e, object) => {
      const { gameType, tableId } = e as CasinoTableExtras;
      if (wallet.balance < 10) wallet.set(10_000); // play money only: top the stack back up
      // seat: the table's authored seat + focus anchors; otherwise the player's side, looking at the centre
      const anchors = zones.anchorsFor(tableId);
      const seatA = anchors.find((a) => a.role === 'seat')?.node, focusA = anchors.find((a) => a.role === 'focus')?.node;
      let seat: Vector3, lookAt: Vector3;
      if (seatA && focusA) {
        seat = seatA.getWorldPosition(new Vector3());
        lookAt = focusA.getWorldPosition(new Vector3());
      } else {
        const box = new Box3().setFromObject(object);
        const centre = box.getCenter(new Vector3());
        const dir = new Vector3(player.position.x - centre.x, 0, player.position.z - centre.z).normalize();
        const reach = gameType === 'slots' ? 0.95 : halfExtent(box, dir) + 0.55;
        seat = centre.clone().addScaledVector(dir, reach).setY(gameType === 'slots' ? 1.32 : 1.28);
        lookAt = centre.clone().setY(gameType === 'slots' ? 1.4 : 0.78);
      }
      fpCamera.setSeat({ position: seat, lookAt, fov: SEAT_FOV[gameType] });
      // table lamp: a soft warm downlight over the play area while seated (cards and chips must read)
      targetExposure = SEAT_EXPOSURE[gameType] ?? 1;   // the eye adapts to a brightly lit table
      const lamp = TABLE_LAMP[gameType];
      lights.setFeature(lamp ? {
        id: `TableLamp_${tableId}`, kind: 'spot', color: 0xffe4bc, intensity: lamp.cd, range: lamp.height + 3,
        position: { x: lookAt.x, y: lookAt.y + lamp.height, z: lookAt.z }, target: { x: lookAt.x, y: lookAt.y, z: lookAt.z },
        angle: lamp.angle, penumbra: 0.75,
      } : null);
      const dim = OVERHEAD_DIM[gameType];
      lights.setDim(dim ? { x: lookAt.x, z: lookAt.z } : null, 2.2, dim ?? 1);   // the fittings right over this table
      seatedAt = tableId;
      seatedGame = gameType;
      gameView.present = (state, events) => zones.gameState(tableId, state, events);
      gameView.onEvents = (events) => {
        for (const ev of events) {
          zones.gameEvent(tableId, ev);
          const at = { x: lookAt.x, y: lookAt.y, z: lookAt.z };
          if (ev.type === 'dealt' || ev.type === 'card' || ev.type === 'reveal' || ev.type === 'street' || ev.type === 'coup') audio?.play('cardFlick', at, 0.6);
          if (ev.type === 'betPlaced' || ((ev.type === 'settled' || ev.type === 'showdown' || ev.type === 'coup') && Number(ev.payout) > 0)) audio?.play('chips', at, 0.7);
          if (ev.type === 'spin' && gameType === 'roulette') audio?.play('rouletteBall', at, 0.8);
          if (ev.type === 'spin' && gameType === 'slots') audio?.play(Number(ev.win) > 0 ? 'slotWin' : 'slotChime', at, 0.7);
        }
      };
      hud.setInGame(true);
      document.exitPointerLock();
      gameView.show(sessions.open(tableId, gameType), tableId.replace(/^\w+_0?/, 'Table '));
    },
  });

  hud.setStatus('Lighting the chandeliers…');
  const t0 = performance.now();
  const start = await zones.loadNow(startZone(manifest));
  player.position = { ...start.spawn!.position };
  player.yaw = start.spawn!.yaw;
  fpCamera.update(0);
  post.setTier(tier);
  await renderer.compileAsync(scene, fpCamera.camera);
  if (__DEBUG__) console.info(`[load] ${start.id} ready in ${(performance.now() - t0).toFixed(0)} ms`);

  // order matters: input → simulation → world state → presentation
  const loop = new FrameLoop().add(controller).add(doors).add(zones).add(lights).add(fpCamera).add(interaction).add(audio);

  let debug: import('./debug/overlay').DebugOverlay | null = null;
  if (__DEBUG__) {
    const { DebugOverlay } = await import('./debug/overlay');
    debug = new DebugOverlay(renderer, scene, player, {
      backend,
      zone: () => `${zones.currentTitle} (${zones.currentId})`,
      zones: () => zones.describe(),
      lights: () => lights.stats,
      tier: () => tier,
      textureMB: textures.totalBytes / 1048576,
      colliders: () => zones.activeColliders,
    }, config.debug);
    loop.add(debug);
    if (config.debug) debug.setColliders(true);
    // automation handle for browser tests (dev builds only): teleport, inspect zones, drive a seated game
    (window as unknown as Record<string, unknown>).__mansion = { player, input, zones, interaction, gameView, renderer, lights, debug };
  }

  addEventListener('resize', () => {
    renderer.setSize(innerWidth, innerHeight, false);
    fpCamera.resize(innerWidth, innerHeight);
  });

  let lastT = 0;
  renderer.setAnimationLoop((t) => {
    const dt = Math.min(0.1, (t - lastT) / 1000);
    lastT = t;
    post.exposure.value += (targetExposure - post.exposure.value) * (1 - Math.exp(-2.5 * dt));
    if (__DEBUG__ && debug && input.pressed('debug')) debug.toggle();
    loop.tick(t);
    post.render();
    input.endFrame();
  });

  hud.ready();
  bus.emit('app:ready');
  if (__DEBUG__) Object.assign(window, { __casino: { renderer, scene, player, zones, doors, lights, camera: fpCamera.camera, post, sessions, wallet, gameView, interaction, audio } });
}

/** Seated field of view per game: a gentle lean-in so cards, reels and the wheel read at play distance. */
const SEAT_FOV: Record<string, number> = { blackjack: 50, baccarat: 44, poker: 48, roulette: 56, slots: 54 };
/** Seated exposure (eye adaptation to a brightly lit table): the felt keeps its colour, cards their pips. */
const CARD_TABLE_DIM = 0.7;   // card games: all light on the table 30 % down while playing
const SEAT_EXPOSURE: Record<string, number> = {
  blackjack: 0.9 * CARD_TABLE_DIM, baccarat: 0.62, poker: 0.72, roulette: 0.85,   // poker/baccarat: OVERHEAD_DIM does the dimming
};
/**
 * While playing, the room's own fittings right over the table (poker pendants, the baccarat chandelier) are
 * dimmed to this fraction: they put a hot spot on white cards and chips that exposure alone can't fix.
 */
const OVERHEAD_DIM: Record<string, number | undefined> = { poker: 0.15, baccarat: 0.15 };
/** Seated table lamp per game (candela, height above the felt, cone half-angle); slots light themselves. */
const TABLE_LAMP: Record<string, { cd: number; height: number; angle: number } | undefined> = {
  blackjack: { cd: 18, height: 1.9, angle: 0.62 }, baccarat: undefined, // the grand chandelier hangs right over it
  poker: undefined, // the brass pendants already light each poker table
  roulette: { cd: 32, height: 2.6, angle: 0.8 },
};

/** Half-extent of an axis-aligned box along a horizontal direction. */
function halfExtent(box: Box3, dir: Vector3): number {
  return Math.abs(dir.x) * (box.max.x - box.min.x) / 2 + Math.abs(dir.z) * (box.max.z - box.min.z) / 2;
}

/** Play-chip stack remembered per browser (a convenience only — never real money, §1). */
function loadChips(): number {
  try {
    const v = Number(localStorage.getItem('riviera.chips'));
    return Number.isFinite(v) && v > 0 ? v : 10_000;
  } catch { return 10_000; }
}
function saveChips(n: number): void {
  try { localStorage.setItem('riviera.chips', String(n)); } catch { /* private mode etc. */ }
}

main().catch((err) => {
  console.error(err);
  const s = document.getElementById('curtain-status');
  if (s) s.textContent = `Something went wrong: ${err instanceof Error ? err.message : err}`;
});
