import { Box3, Color, Scene, Vector3 } from 'three/webgpu';
import { readConfig } from './core/config';
import { EventBus, type QualityTier } from './core/events';
import { FrameLoop } from './core/loop';
import { FirstPersonCamera } from './camera/firstPersonCamera';
import { InteractionSystem } from './interaction/interactionSystem';
import { TextureLibrary } from './loading/textureLibrary';
import { LightPool } from './render/lightPool';
import { createMaterials } from './render/materials';
import { loadArt } from './render/art';
import { ProbeManager } from './render/probe';
import { createRenderer, PostStack } from './render/renderer';
import { PlayerController, createPlayerState } from './player/controller';
import { Input } from './player/input';
import { DoorSystem } from './world/doors';
import { initGlbLoader } from './loading/glbZone';
import { buildZoneGraph, type AssetManifest } from './world/zoneGraph';
import { ZoneManager } from './world/zoneManager';
import { Hud } from './ui/hud';
import { AudioEngine } from './audio/audioEngine';
import { GameView } from './ui/gameView';
import { registerGames } from './games/registry';
import { GameSessionManager, Wallet } from './games/shared/session';
import type { CasinoTableExtras } from './interaction/schema';
import { assetUrl } from './loading/assetUrl';

async function main() {
  const config = readConfig();
  const bus = new EventBus();
  const canvas = document.getElementById('viewport') as HTMLCanvasElement;

  const input = new Input(canvas);
  let tier: QualityTier = config.quality;

  const { renderer, backend } = await createRenderer(canvas, config.forceWebGL);
  const scene = new Scene();
  scene.background = new Color(0x050302);

  const player = createPlayerState({ x: 0, y: 0, z: 0 }, 0);
  const fpCamera = new FirstPersonCamera(player);
  const post = new PostStack(renderer, scene, fpCamera.camera);

  let audio: AudioEngine | null = null;
  const hud = new Hud(bus, {
    requestLock: () => { audio?.start(); void input.lock(); }, // user gesture: also unlocks audio
    setVolume: (v) => audio?.setVolume(v),
    setQuality: (t) => { tier = t; post.setTier(t); bus.emit('quality:changed', { tier: t }); },
    setSensitivity: (v) => { input.sensitivity = v; },
    setFov: (v) => fpCamera.setFov(v),
  }, tier);
  document.addEventListener('pointerlockchange', () => hud.setLocked(input.isLocked));

  // ---- initial load: textures → materials → lobby only; the rest of the mansion streams (§8)
  hud.setStatus('Polishing the marble…');
  const textures = new TextureLibrary(renderer.getMaxAnisotropy());
  await Promise.all([
    textures.load(assetUrl('/assets/textures/textures.json'), (d, t) => hud.setStatus(`Polishing the marble… ${Math.round((d / t) * 100)}%`)),
    document.fonts.load("500 48px 'Cinzel'"), // door plaques are drawn with it
    loadArt(assetUrl('/assets/art/art.json'), renderer.getMaxAnisotropy()),
  ]);
  const materials = createMaterials(textures);
  initGlbLoader(renderer);
  // generated by `npm run build:assets`; the mansion still works (code zones only) without it
  const manifest: AssetManifest = await fetch(assetUrl('/assets/manifest.json')).then((r) => (r.ok ? r.json() : { zones: {} }), () => ({ zones: {} }));

  const lights = new LightPool(scene, fpCamera.camera);
  const probes = new ProbeManager(renderer, scene, 0.35);
  const interaction = new InteractionSystem(fpCamera.camera, input, bus);
  const zones = new ZoneManager(buildZoneGraph(manifest), { scene, renderer, camera: fpCamera.camera, bus, player, materials, lights, probes, interaction });
  const doors = new DoorSystem(zones, player, bus);
  zones.doors = doors;
  interaction.register('door', {
    prompt: (e) => doors.promptFor(String(e.doorId)),
    activate: (e) => doors.activate(String(e.doorId)),
  });
  const controller = new PlayerController(player, input, zones.collisionWorld);

  // ---- audio (Phase 6): zone beds, positional emitters, door + game sounds
  audio = new AudioEngine(fpCamera.camera, () => zones.visibleSounds());
  bus.on('zone:entered', ({ zoneId }) => audio?.setZone(zoneId));
  bus.on('door:moved', ({ opening, position }) => audio?.play(opening ? 'doorOpen' : 'doorClose', { ...position, y: 1.5 }, 0.8));
  addEventListener('keydown', (e) => {
    if (e.code === 'KeyM' && !e.repeat && audio) bus.emit('ui:toast', { text: audio.toggleMute() ? 'Sound muted — press M to restore' : 'Sound on' });
  });

  // ---- games (Phase 5): world → interaction → session → engine; the UI only presents (§9)
  const wallet = new Wallet(loadChips());
  const sessions = new GameSessionManager(wallet, Math.random);
  registerGames(sessions);
  const gameView = new GameView(wallet);
  let seatedAt: string | null = null;
  const leaveTable = () => {
    if (!seatedAt) return;
    sessions.close(seatedAt);
    seatedAt = null;
    saveChips(wallet.balance);
    gameView.hide();
    fpCamera.setSeat(null);
    hud.setInGame(false);
    // Re-lock the mouse; if the browser refuses (e.g. the gesture was Esc), fall back to the pause menu.
    void input.lock().finally(() => setTimeout(() => { if (!input.isLocked) hud.setLocked(false); }, 250));
  };
  gameView.onLeave = leaveTable;
  interaction.register('casinoTable', {
    prompt: (e) => e.interactionPrompt,
    activate: (e, object) => {
      const { gameType, tableId } = e as CasinoTableExtras;
      if (wallet.balance < 10) wallet.set(10_000); // play money only: top the stack back up
      // seat: on the player's side of the table, looking at its centre
      const box = new Box3().setFromObject(object);
      const centre = box.getCenter(new Vector3());
      const dir = new Vector3(player.position.x - centre.x, 0, player.position.z - centre.z).normalize();
      const reach = gameType === 'slots' ? 0.95 : halfExtent(box, dir) + 0.55;
      const seat = centre.clone().addScaledVector(dir, reach).setY(gameType === 'slots' ? 1.32 : 1.28);
      const lookAt = centre.clone().setY(gameType === 'slots' ? 1.4 : 0.78);
      fpCamera.setSeat({ position: seat, lookAt });
      seatedAt = tableId;
      gameView.onEvents = (events) => {
        for (const ev of events) {
          zones.gameEvent(tableId, ev);
          const at = { x: lookAt.x, y: lookAt.y, z: lookAt.z };
          if (ev.type === 'dealt' || ev.type === 'card' || ev.type === 'reveal' || ev.type === 'street' || ev.type === 'coup') audio?.play('cardFlick', at, 0.6);
          if (ev.type === 'betPlaced' || ((ev.type === 'settled' || ev.type === 'showdown' || ev.type === 'coup') && Number(ev.payout) > 0)) audio?.play('chips', at, 0.7);
          if (ev.type === 'spin' && gameType === 'roulette') audio?.play('rouletteBall', at, 0.8);
          if (ev.type === 'spin' && gameType === 'slots') audio?.play(Number(ev.win) > 0 ? 'slotWin' : 'slotChime', at, 0.7);
        }
      };
      hud.setInGame(true);
      document.exitPointerLock();
      gameView.show(sessions.open(tableId, gameType), tableId.replace(/^\w+_0?/, 'Table '));
    },
  });

  hud.setStatus('Lighting the chandeliers…');
  const t0 = performance.now();
  const lobby = await zones.loadNow('lobby');
  player.position = { ...lobby.spawn!.position };
  player.yaw = lobby.spawn!.yaw;
  fpCamera.update(0);
  post.setTier(tier);
  await renderer.compileAsync(scene, fpCamera.camera);
  if (__DEBUG__) console.info(`[load] lobby ready in ${(performance.now() - t0).toFixed(0)} ms`);

  // order matters: input → simulation → world state → presentation
  const loop = new FrameLoop().add(controller).add(doors).add(zones).add(lights).add(fpCamera).add(interaction).add(audio);

  let debug: import('./debug/overlay').DebugOverlay | null = null;
  if (__DEBUG__) {
    const { DebugOverlay } = await import('./debug/overlay');
    debug = new DebugOverlay(renderer, scene, player, {
      backend,
      zone: () => `${zones.currentTitle} (${zones.currentId})`,
      zones: () => zones.describe(),
      lights: () => lights.stats,
      tier: () => tier,
      textureMB: textures.totalBytes / 1048576,
      colliders: () => zones.activeColliders,
    }, config.debug);
    loop.add(debug);
    if (config.debug) debug.setColliders(true);
  }

  addEventListener('resize', () => {
    renderer.setSize(innerWidth, innerHeight, false);
    fpCamera.resize(innerWidth, innerHeight);
  });

  renderer.setAnimationLoop((t) => {
    if (__DEBUG__ && debug && input.pressed('debug')) debug.toggle();
    loop.tick(t);
    post.render();
    input.endFrame();
  });

  hud.ready();
  bus.emit('app:ready');
  if (__DEBUG__) Object.assign(window, { __casino: { renderer, scene, player, zones, doors, lights, camera: fpCamera.camera, post, sessions, wallet, gameView, interaction, audio } });
}

/** Half-extent of an axis-aligned box along a horizontal direction. */
function halfExtent(box: Box3, dir: Vector3): number {
  return Math.abs(dir.x) * (box.max.x - box.min.x) / 2 + Math.abs(dir.z) * (box.max.z - box.min.z) / 2;
}

/** Play-chip stack remembered per browser (a convenience only — never real money, §1). */
function loadChips(): number {
  try {
    const v = Number(localStorage.getItem('riviera.chips'));
    return Number.isFinite(v) && v > 0 ? v : 10_000;
  } catch { return 10_000; }
}
function saveChips(n: number): void {
  try { localStorage.setItem('riviera.chips', String(n)); } catch { /* private mode etc. */ }
}

main().catch((err) => {
  console.error(err);
  const s = document.getElementById('curtain-status');
  if (s) s.textContent = `Something went wrong: ${err instanceof Error ? err.message : err}`;
});
